---

- name: Create Grafana directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    mode: "0755"
  loop:
    - "{{ app_folder }}"
    - "{{ conf_folder }}"
    - "{{ data_folder }}"

- name: Download and unarchive Node Exporter
  unarchive:
    src: "{{ node_exporter_download_url }}"
    dest: /tmp/node_exporter-{{ node_exporter_version }}.linux-amd64
    remote_src: yes
    mode: "0755"

- name: Copy binary to {{ app_folder }}
  copy:
    src: "/tmp/node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter"
    dest: "{{ app_folder }}"
    owner: "{{ node_exporter_user }}"
    group: "{{ node_exporter_group }}"
    mode: '0755'
    remote_src: yes
    extra_opts:
      - --strip-components=1    

- name: Create systemd service unit
  template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
    owner: root
    group: root
    mode: '0644'
  notify:
    - reload systemd
    - enable node_exporter
    - restart node_exporter
