---

node_exporter_version: "1.8.2"

node_exporter_user: "{{ odoo_user }}"
node_exporter_group: "{{odoo_group }}"

# Custom Paths
app_folder: "/apps/prometheus"
conf_folder: "{{ app_folder }}/conf"
data_folder: "/data/prometheus"

node_exporter_host: 0.0.0.0
node_exporter_port: 9100
node_exporter_options: ''

node_exporter_download_url: https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz
