app_folder: /apps/odoo
data_folder: /data/odoo

odoo_user: odoo
odoo_home: "{{ app_folder }}"
odoo_version: "17.0"
odoo_repo: https://github.com/odoo/odoo.git

odoo_env: production

# FreeIPA / LDAP Settings
ldap_enabled: true
ldap_server: ipa.cabinetblessingconsulting.intra
ldap_port: 636
ldap_use_ssl: true
ldap_bind_dn: uid=odoo-bind,cn=users,cn=accounts,dc=cabinetblessingconsulting,dc=intra
ldap_bind_password: odoo # change this password
ldap_base_dn: cn=users,cn=accounts,dc=cabinetblessingconsulting,dc=intra
ldap_filter: (&(uid=%s)(memberOf=cn=odoo-users,cn=groups,cn=accounts,dc=cabinetblessingconsulting,dc=intra))

# odoo public domain
public_domain: odoo.cabinetblessingconsulting.com