# Internal IPs for the HAProxy Backend configuration
app_servers:
  - name: odoo-app1
    ip: 10.0.1.3
    
  - name: odoo-app2
    ip: 10.0.1.4

# The Customer Master List
customers:
  - name: veto-yaounde
    port: 8069
    db_user: veto_yaounde_user
    db_name: veto_yaounde
    db_password: yaounde # don't forget to change this password
    public_url: veto-yde.{{ public_domain }}
  
  - name: veto-bafoussam
    port: 8070
    db_user: veto_bafoussam_user
    db_name: veto_bafoussam
    db_password: bafoussam # don't forget to change this password
    public_url: veto-baf.{{ public_domain }}    
