
odoo_home: "{{ app_folder }}"
odoo_version: "15.0"
odoo_repo: https://github.com/odoo/odoo.git

odoo_env: production

# FreeIPA / LDAP Settings

ldap_filter: (&(uid=%s)(memberOf=cn=odoo-users,cn=groups,cn=accounts,dc=cabinetblessingconsulting,dc=intra))

db_host_internal: 10.1.1.2         # Internal IP of your Postgres Server

internal_domain: odoo.cabinetblessingconsulting.intra
