
env: prod
odoo_user: odoo
odoo_group: odoo

ldap_enabled: true
ldap_server: ipa.cabinetblessingconsulting.intra
ldap_port: 636
ldap_use_ssl: true

ldap_bind_dn: uid=odoo-bind,cn=users,cn=accounts,dc=cabinetblessingconsulting,dc=intra
ldap_bind_password: odoo # change this password
ldap_base_dn: cn=users,cn=accounts,dc=cabinetblessingconsulting,dc=intra
ldap_search_query: (&(uid=%s)(memberOf=cn=vpnusers,cn=groups,cn=accounts,dc=cabinetblessingconsulting,dc=intra))

# odoo public domain
public_domain: odoo.cabinetblessingconsulting.com

odoo_workers: 0

smb_share: /mnt/blessing/applis/addons
creds_addons: /root/.credentials

shares:
  - name: "addons_share"
    type: "cifs"
    src: "//u529061.your-storagebox.de/backup"
    mount_point: "{{ smb_share }}"
    opts: "cache=none,rw,credentials={{ creds_addons }}/{{ odoo_user }},file_mode=0660,dir_mode=0777"
# The Customer Master List

pgbouncer_port: 6432

customers:
  - name: veto
    port: 8074
    db_user: veto
    db_name: veto
    db_password: veto # don't forget to change this password
    public_url: veto.{{ public_domain }}
    db_init_data: present   # present | absent | creat
    addon_path: "{{ app_folder }}/custom/veto/"
  
  - name: classic
    port: 8075
    db_user: classic
    db_name: classic
    db_password: classic # don't forget to change this password
    public_url: classic.{{ public_domain }}   
    db_init_data: present   # present | absent | recreate 
    addon_path: "{{ app_folder }}/custom/classic"
  

#  - name: veto_yaounde
#    port: 8069
#    db_user: veto_yaounde
#    db_name: veto_yaounde
#    db_password: veto_yaounde # don't forget to change this password
#    public_url: veto-yde.{{ public_domain }}
#    db_init_data: absent   # present | absent | create
#  
#  - name: veto_bafoussam
#    port: 8070
#    db_user: veto_bafoussam
#    db_name: veto_bafoussam
#    db_password: veto_bafoussam # don't forget to change this password
#    public_url: veto-baf.{{ public_domain }}   
#    db_init_data: absent   # present | absent | recreate 
#
#  - name: classic_mbouda
#    port: 8071
#    db_user: classic_mbouda
#    db_name: classic_mbouda
#    db_password: classic_mbouda # don't forget to change this password
#    public_url: classic-mda.{{ public_domain }}
#    db_init_data: create   # present | absent | recreate    
#
#  - name: classic_yaounde
#    port: 8072
#    db_user: classic_yaounde
#    db_name: classic_yaounde
#    db_password: classic_yaounde # don't forget to change this password
#    public_url: classic-yde.{{ public_domain }}
#    db_init_data: create   # present | absent | recreate
#  
#  - name: classic_garouaboulai
#    port: 8073
#    db_user: classic_garouaboulai
#    db_name: classic_garouaboulai
#    db_password: classic_garouaboulai # don't forget to change this password
#    public_url: classic-grb.{{ public_domain }}
#    db_init_data: create   # present | absent | recreate